// <auto-generated />
using System;
using HospitalTaskManagerWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalTaskManagerWebAPI.Migrations
{
    [DbContext(typeof(HospitalTaskManagerContext))]
    [Migration("20200511103554_newseed")]
    partial class newseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentName = "Coola avdelningen"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentName = "Mindre coola avdelningen"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsHandled");

                    b.Property<string>("ProcedureName");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("StaffID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.Property<int>("ScheduleId");

                    b.Property<int>("ProcedureId");

                    b.Property<bool>("KeyPerson");

                    b.HasKey("ScheduleId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("ScheduledProcedures");
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("OnSite");

                    b.Property<string>("PhoneNr");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Mario",
                            OnSite = true,
                            PhoneNr = "0704499449"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0701806573"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0709926135"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0705959157"
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Krunkenstör",
                            OnSite = true,
                            PhoneNr = "0707308269"
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0702398987"
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0705228959"
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0709169682"
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0708606453"
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0709185486"
                        },
                        new
                        {
                            ID = 11,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0708566462"
                        },
                        new
                        {
                            ID = 12,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0708563408"
                        },
                        new
                        {
                            ID = 13,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0703431240"
                        },
                        new
                        {
                            ID = 14,
                            DepartmentId = 1,
                            FirstName = "Stina",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0708429447"
                        },
                        new
                        {
                            ID = 15,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0703023054"
                        },
                        new
                        {
                            ID = 16,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0705242940"
                        },
                        new
                        {
                            ID = 17,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0708886625"
                        },
                        new
                        {
                            ID = 18,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0702027443"
                        },
                        new
                        {
                            ID = 19,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Mario",
                            OnSite = true,
                            PhoneNr = "0703439282"
                        },
                        new
                        {
                            ID = 20,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0708802916"
                        },
                        new
                        {
                            ID = 21,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0704154185"
                        },
                        new
                        {
                            ID = 22,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0705376397"
                        },
                        new
                        {
                            ID = 23,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0703710514"
                        },
                        new
                        {
                            ID = 24,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0709705386"
                        },
                        new
                        {
                            ID = 25,
                            DepartmentId = 1,
                            FirstName = "Stina",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0706167369"
                        },
                        new
                        {
                            ID = 26,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Skraputnik",
                            OnSite = true,
                            PhoneNr = "0705287178"
                        },
                        new
                        {
                            ID = 27,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0709214423"
                        },
                        new
                        {
                            ID = 28,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0705173032"
                        },
                        new
                        {
                            ID = 29,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0707642468"
                        },
                        new
                        {
                            ID = 30,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Skraputnik",
                            OnSite = true,
                            PhoneNr = "0706375412"
                        },
                        new
                        {
                            ID = 31,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0708832478"
                        },
                        new
                        {
                            ID = 32,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0701465453"
                        },
                        new
                        {
                            ID = 33,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0703207589"
                        },
                        new
                        {
                            ID = 34,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0704773253"
                        },
                        new
                        {
                            ID = 35,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Kvackzelius",
                            OnSite = true,
                            PhoneNr = "0707619485"
                        },
                        new
                        {
                            ID = 36,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0704949245"
                        },
                        new
                        {
                            ID = 37,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0706977795"
                        },
                        new
                        {
                            ID = 38,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0708469235"
                        },
                        new
                        {
                            ID = 39,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0708445819"
                        },
                        new
                        {
                            ID = 40,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0708535555"
                        },
                        new
                        {
                            ID = 41,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0708105371"
                        },
                        new
                        {
                            ID = 42,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0702558023"
                        },
                        new
                        {
                            ID = 43,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0701303179"
                        },
                        new
                        {
                            ID = 44,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0706517545"
                        },
                        new
                        {
                            ID = 45,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Skraputnik",
                            OnSite = true,
                            PhoneNr = "0704844036"
                        },
                        new
                        {
                            ID = 46,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0706584869"
                        },
                        new
                        {
                            ID = 47,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0705674124"
                        },
                        new
                        {
                            ID = 48,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0707385017"
                        },
                        new
                        {
                            ID = 49,
                            DepartmentId = 1,
                            FirstName = "Stina",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0708121391"
                        },
                        new
                        {
                            ID = 50,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0703047691"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Procedures")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Staff", "Staff")
                        .WithMany("Schedules")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Procedure", "Procedure")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalTaskManagerWebAPI.Models.Schedule", "Schedule")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
