// <auto-generated />
using System;
using HospitalTaskManagerWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalTaskManagerWebAPI.Migrations
{
    [DbContext(typeof(HospitalTaskManagerContext))]
    [Migration("20200511104353_newerseed")]
    partial class newerseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentName = "Coola avdelningen"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentName = "Mindre coola avdelningen"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsHandled");

                    b.Property<string>("ProcedureName");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ge filiduttvaccin",
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Dyrka Satan",
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Operation",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skriva ut krumelurpiller",
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Dyrka Satan",
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Dyrka Satan",
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skriva ut krumelurpiller",
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Dyrka Satan",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 51,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 52,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 53,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 54,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 55,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Operation",
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 56,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 57,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 58,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 59,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skriva ut krumelurpiller",
                            StartDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 60,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("StaffID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 1,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 2,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 3,
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 4,
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 5,
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            EndDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 6,
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 7,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 8,
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 9,
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 10,
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 11,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 12,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 13,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 14,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 15,
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 16,
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 17,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 18,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 19,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 20,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            EndDate = new DateTime(2020, 5, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 21,
                            StartDate = new DateTime(2020, 5, 11, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 22,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 23,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 24,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 25,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            EndDate = new DateTime(2020, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 26,
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 27,
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            EndDate = new DateTime(2020, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 28,
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 29,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 30,
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 31,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            EndDate = new DateTime(2020, 5, 11, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 32,
                            StartDate = new DateTime(2020, 5, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 33,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            EndDate = new DateTime(2020, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 34,
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 35,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 36,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            EndDate = new DateTime(2020, 5, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 37,
                            StartDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 38,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            EndDate = new DateTime(2020, 5, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 39,
                            StartDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 40,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 41,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 42,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            EndDate = new DateTime(2020, 5, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 43,
                            StartDate = new DateTime(2020, 5, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            EndDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 44,
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 45,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            EndDate = new DateTime(2020, 5, 11, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 46,
                            StartDate = new DateTime(2020, 5, 11, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            EndDate = new DateTime(2020, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 47,
                            StartDate = new DateTime(2020, 5, 11, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 48,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            EndDate = new DateTime(2020, 5, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 49,
                            StartDate = new DateTime(2020, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            EndDate = new DateTime(2020, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 50,
                            StartDate = new DateTime(2020, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.Property<int>("ScheduleId");

                    b.Property<int>("ProcedureId");

                    b.Property<bool>("KeyPerson");

                    b.HasKey("ScheduleId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("ScheduledProcedures");
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("OnSite");

                    b.Property<string>("PhoneNr");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Filling",
                            OnSite = false,
                            PhoneNr = "0704410651"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0701345407"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Mario",
                            OnSite = true,
                            PhoneNr = "0709957172"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0708931183"
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 1,
                            FirstName = "Stina",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0707327461"
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0709680944"
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0705585897"
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0705537208"
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Skraputnik",
                            OnSite = true,
                            PhoneNr = "0707250114"
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0703720361"
                        },
                        new
                        {
                            ID = 11,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0704802627"
                        },
                        new
                        {
                            ID = 12,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0706322585"
                        },
                        new
                        {
                            ID = 13,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0702983046"
                        },
                        new
                        {
                            ID = 14,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0709680304"
                        },
                        new
                        {
                            ID = 15,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0709264376"
                        },
                        new
                        {
                            ID = 16,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0706889538"
                        },
                        new
                        {
                            ID = 17,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Kvackzelius",
                            OnSite = true,
                            PhoneNr = "0704775990"
                        },
                        new
                        {
                            ID = 18,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0702865234"
                        },
                        new
                        {
                            ID = 19,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0708570650"
                        },
                        new
                        {
                            ID = 20,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Kvackzelius",
                            OnSite = true,
                            PhoneNr = "0707969173"
                        },
                        new
                        {
                            ID = 21,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0701252195"
                        },
                        new
                        {
                            ID = 22,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0702196057"
                        },
                        new
                        {
                            ID = 23,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0708542166"
                        },
                        new
                        {
                            ID = 24,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Lannister",
                            OnSite = true,
                            PhoneNr = "0709389473"
                        },
                        new
                        {
                            ID = 25,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0704594357"
                        },
                        new
                        {
                            ID = 26,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0705029892"
                        },
                        new
                        {
                            ID = 27,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0707023751"
                        },
                        new
                        {
                            ID = 28,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0704073140"
                        },
                        new
                        {
                            ID = 29,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0709893576"
                        },
                        new
                        {
                            ID = 30,
                            DepartmentId = 1,
                            FirstName = "Kalle",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0709427879"
                        },
                        new
                        {
                            ID = 31,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Krunkenstör",
                            OnSite = true,
                            PhoneNr = "0701938330"
                        },
                        new
                        {
                            ID = 32,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0702796340"
                        },
                        new
                        {
                            ID = 33,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0707000604"
                        },
                        new
                        {
                            ID = 34,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0708453924"
                        },
                        new
                        {
                            ID = 35,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0703933738"
                        },
                        new
                        {
                            ID = 36,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0707750792"
                        },
                        new
                        {
                            ID = 37,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0709268524"
                        },
                        new
                        {
                            ID = 38,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0704463247"
                        },
                        new
                        {
                            ID = 39,
                            DepartmentId = 1,
                            FirstName = "CourageWolf",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0703686907"
                        },
                        new
                        {
                            ID = 40,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0704388800"
                        },
                        new
                        {
                            ID = 41,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0702748815"
                        },
                        new
                        {
                            ID = 42,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0708570934"
                        },
                        new
                        {
                            ID = 43,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0702514154"
                        },
                        new
                        {
                            ID = 44,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0708649922"
                        },
                        new
                        {
                            ID = 45,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0709059653"
                        },
                        new
                        {
                            ID = 46,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Adrafsfader",
                            OnSite = true,
                            PhoneNr = "0708436052"
                        },
                        new
                        {
                            ID = 47,
                            DepartmentId = 1,
                            FirstName = "Super",
                            LastName = "Mario",
                            OnSite = true,
                            PhoneNr = "0701193120"
                        },
                        new
                        {
                            ID = 48,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0701923050"
                        },
                        new
                        {
                            ID = 49,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0704916469"
                        },
                        new
                        {
                            ID = 50,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Skraputnik",
                            OnSite = true,
                            PhoneNr = "0707539431"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Procedures")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Staff", "Staff")
                        .WithMany("Schedules")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Procedure", "Procedure")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalTaskManagerWebAPI.Models.Schedule", "Schedule")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
