// <auto-generated />
using System;
using HospitalTaskManagerWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalTaskManagerWebAPI.Migrations
{
    [DbContext(typeof(HospitalTaskManagerContext))]
    [Migration("20200516080728_newestseed")]
    partial class newestseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName");

                    b.HasKey("ID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentName = "Coola avdelningen"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentName = "Mindre coola avdelningen"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("IsHandled");

                    b.Property<string>("ProcedureName");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Botoxa stortår",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Operation",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skälla ut praktikanten",
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Botoxa stortår",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Operation",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Lungmätning",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Laga stormiddag",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Rutinkontroll",
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ge filiduttvaccin",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tömma ryggradsvätska",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Botoxa stortår",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ögonkorrigering",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Lungmätning",
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 51,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Skapa vaccin för kåråna",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 52,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Botoxa stortår",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 53,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Programmera statuslistan",
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 54,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Ge filiduttvaccin",
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 55,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Tandskrapning",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 56,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Injicera dunderhonung",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 57,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Operation",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 58,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Knäskålsrekonstruktion",
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 59,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Genkodning",
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 60,
                            DepartmentId = 1,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHandled = false,
                            ProcedureName = "Öronkontroll",
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("StaffID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 1,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 2,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 3,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            EndDate = new DateTime(2020, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 4,
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 5,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 6,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 7,
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 8,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            EndDate = new DateTime(2020, 5, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 9,
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 10,
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 11,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 12,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 13,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 14,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 15,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 16,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            EndDate = new DateTime(2020, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 17,
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 18,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 19,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 20,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 21,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 22,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 23,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 24,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 25,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 26,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 27,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 28,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 29,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 30,
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 31,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 32,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 33,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 34,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 35,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 36,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 37,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 38,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 39,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 40,
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            EndDate = new DateTime(2020, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 41,
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 42,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 43,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 44,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            EndDate = new DateTime(2020, 5, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 45,
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 46,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 47,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 48,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            EndDate = new DateTime(2020, 5, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 49,
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            EndDate = new DateTime(2020, 5, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 50,
                            StartDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 51,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 51,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 52,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 52,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 53,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 53,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 54,
                            EndDate = new DateTime(2020, 5, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 54,
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 55,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 55,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 56,
                            EndDate = new DateTime(2020, 5, 16, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 56,
                            StartDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 57,
                            EndDate = new DateTime(2020, 5, 16, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 57,
                            StartDate = new DateTime(2020, 5, 16, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 58,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 58,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 59,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 59,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 60,
                            EndDate = new DateTime(2020, 5, 16, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 60,
                            StartDate = new DateTime(2020, 5, 16, 6, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 61,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 61,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 62,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 62,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 63,
                            EndDate = new DateTime(2020, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 63,
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 64,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 64,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 65,
                            EndDate = new DateTime(2020, 5, 16, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 65,
                            StartDate = new DateTime(2020, 5, 16, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 66,
                            EndDate = new DateTime(2020, 5, 16, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 66,
                            StartDate = new DateTime(2020, 5, 16, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 67,
                            EndDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 67,
                            StartDate = new DateTime(2020, 5, 16, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 68,
                            EndDate = new DateTime(2020, 5, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 68,
                            StartDate = new DateTime(2020, 5, 16, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 69,
                            EndDate = new DateTime(2020, 5, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 69,
                            StartDate = new DateTime(2020, 5, 16, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 70,
                            EndDate = new DateTime(2020, 5, 16, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffID = 70,
                            StartDate = new DateTime(2020, 5, 16, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.Property<int>("ScheduleId");

                    b.Property<int>("ProcedureId");

                    b.Property<bool>("KeyPerson");

                    b.HasKey("ScheduleId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("ScheduledProcedures");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            ProcedureId = 1,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 2,
                            ProcedureId = 1,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 2,
                            ProcedureId = 2,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 1,
                            ProcedureId = 3,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 1,
                            ProcedureId = 4,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 3,
                            ProcedureId = 5,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 6,
                            ProcedureId = 7,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 5,
                            ProcedureId = 5,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 8,
                            ProcedureId = 10,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 7,
                            ProcedureId = 8,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 7,
                            ProcedureId = 7,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 8,
                            ProcedureId = 9,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 11,
                            ProcedureId = 10,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 12,
                            ProcedureId = 11,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 13,
                            ProcedureId = 13,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 14,
                            ProcedureId = 14,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 15,
                            ProcedureId = 15,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 16,
                            ProcedureId = 16,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 17,
                            ProcedureId = 17,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 18,
                            ProcedureId = 18,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 19,
                            ProcedureId = 19,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 20,
                            ProcedureId = 20,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 21,
                            ProcedureId = 21,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 22,
                            ProcedureId = 22,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 23,
                            ProcedureId = 23,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 24,
                            ProcedureId = 24,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 25,
                            ProcedureId = 25,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 26,
                            ProcedureId = 25,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 26,
                            ProcedureId = 26,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 27,
                            ProcedureId = 27,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 28,
                            ProcedureId = 28,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 29,
                            ProcedureId = 29,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 30,
                            ProcedureId = 30,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 31,
                            ProcedureId = 31,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 32,
                            ProcedureId = 32,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 33,
                            ProcedureId = 33,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 34,
                            ProcedureId = 34,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 35,
                            ProcedureId = 35,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 37,
                            ProcedureId = 36,
                            KeyPerson = true
                        },
                        new
                        {
                            ScheduleId = 36,
                            ProcedureId = 37,
                            KeyPerson = true
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("OnSite");

                    b.Property<string>("PhoneNr");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentId = 1,
                            FirstName = "Silver",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0709037319"
                        },
                        new
                        {
                            ID = 2,
                            DepartmentId = 2,
                            FirstName = "Gandalf",
                            LastName = "Krukskalle",
                            OnSite = true,
                            PhoneNr = "0703991945"
                        },
                        new
                        {
                            ID = 3,
                            DepartmentId = 1,
                            FirstName = "Svetlana",
                            LastName = "Gandhi",
                            OnSite = false,
                            PhoneNr = "0702622392"
                        },
                        new
                        {
                            ID = 4,
                            DepartmentId = 2,
                            FirstName = "Carlos",
                            LastName = "Segelspjut",
                            OnSite = false,
                            PhoneNr = "0701795058"
                        },
                        new
                        {
                            ID = 5,
                            DepartmentId = 2,
                            FirstName = "Tyrion",
                            LastName = "Sainz",
                            OnSite = true,
                            PhoneNr = "0707264223"
                        },
                        new
                        {
                            ID = 6,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Filling",
                            OnSite = false,
                            PhoneNr = "0704030363"
                        },
                        new
                        {
                            ID = 7,
                            DepartmentId = 2,
                            FirstName = "Silver",
                            LastName = "Dorian",
                            OnSite = true,
                            PhoneNr = "0708711616"
                        },
                        new
                        {
                            ID = 8,
                            DepartmentId = 2,
                            FirstName = "Sauron",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0708081420"
                        },
                        new
                        {
                            ID = 9,
                            DepartmentId = 2,
                            FirstName = "Silver",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0704978837"
                        },
                        new
                        {
                            ID = 10,
                            DepartmentId = 2,
                            FirstName = "Kalle",
                            LastName = "Gandhi",
                            OnSite = true,
                            PhoneNr = "0702523431"
                        },
                        new
                        {
                            ID = 11,
                            DepartmentId = 2,
                            FirstName = "Katja",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0706218451"
                        },
                        new
                        {
                            ID = 12,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0707785944"
                        },
                        new
                        {
                            ID = 13,
                            DepartmentId = 2,
                            FirstName = "Sauron",
                            LastName = "Daniels",
                            OnSite = true,
                            PhoneNr = "0704852704"
                        },
                        new
                        {
                            ID = 14,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0706283336"
                        },
                        new
                        {
                            ID = 15,
                            DepartmentId = 1,
                            FirstName = "Sauron",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0705754952"
                        },
                        new
                        {
                            ID = 16,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Askrafvsfader",
                            OnSite = true,
                            PhoneNr = "0703233393"
                        },
                        new
                        {
                            ID = 17,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0707433490"
                        },
                        new
                        {
                            ID = 18,
                            DepartmentId = 1,
                            FirstName = "Lisa",
                            LastName = "Krunkenstör",
                            OnSite = false,
                            PhoneNr = "0705853177"
                        },
                        new
                        {
                            ID = 19,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Askrafvsfader",
                            OnSite = false,
                            PhoneNr = "0708377980"
                        },
                        new
                        {
                            ID = 20,
                            DepartmentId = 2,
                            FirstName = "Mario",
                            LastName = "Gandhi",
                            OnSite = true,
                            PhoneNr = "0709480195"
                        },
                        new
                        {
                            ID = 21,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0705953927"
                        },
                        new
                        {
                            ID = 22,
                            DepartmentId = 1,
                            FirstName = "Nikolaj",
                            LastName = "Hormoz",
                            OnSite = true,
                            PhoneNr = "0708280821"
                        },
                        new
                        {
                            ID = 23,
                            DepartmentId = 1,
                            FirstName = "Ali",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0705307237"
                        },
                        new
                        {
                            ID = 24,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Gandhi",
                            OnSite = true,
                            PhoneNr = "0704031493"
                        },
                        new
                        {
                            ID = 25,
                            DepartmentId = 2,
                            FirstName = "Stina",
                            LastName = "Kenttä",
                            OnSite = false,
                            PhoneNr = "0705050064"
                        },
                        new
                        {
                            ID = 26,
                            DepartmentId = 2,
                            FirstName = "Savanna",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0709139384"
                        },
                        new
                        {
                            ID = 27,
                            DepartmentId = 2,
                            FirstName = "Lisa",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0701258856"
                        },
                        new
                        {
                            ID = 28,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Dorian",
                            OnSite = false,
                            PhoneNr = "0702435719"
                        },
                        new
                        {
                            ID = 29,
                            DepartmentId = 2,
                            FirstName = "Stina",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0707082210"
                        },
                        new
                        {
                            ID = 30,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Dorian",
                            OnSite = false,
                            PhoneNr = "0701247488"
                        },
                        new
                        {
                            ID = 31,
                            DepartmentId = 2,
                            FirstName = "Nikolaj",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0709035034"
                        },
                        new
                        {
                            ID = 32,
                            DepartmentId = 2,
                            FirstName = "Svetlana",
                            LastName = "Sainz",
                            OnSite = true,
                            PhoneNr = "0703235656"
                        },
                        new
                        {
                            ID = 33,
                            DepartmentId = 2,
                            FirstName = "Ali",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0709669695"
                        },
                        new
                        {
                            ID = 34,
                            DepartmentId = 2,
                            FirstName = "Gandalf",
                            LastName = "Sork",
                            OnSite = true,
                            PhoneNr = "0704612832"
                        },
                        new
                        {
                            ID = 35,
                            DepartmentId = 2,
                            FirstName = "Mattias",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0704283018"
                        },
                        new
                        {
                            ID = 36,
                            DepartmentId = 2,
                            FirstName = "Sauron",
                            LastName = "Sainz",
                            OnSite = false,
                            PhoneNr = "0704940880"
                        },
                        new
                        {
                            ID = 37,
                            DepartmentId = 1,
                            FirstName = "Savanna",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0706017866"
                        },
                        new
                        {
                            ID = 38,
                            DepartmentId = 1,
                            FirstName = "Carlos",
                            LastName = "Ramone",
                            OnSite = false,
                            PhoneNr = "0706361656"
                        },
                        new
                        {
                            ID = 39,
                            DepartmentId = 1,
                            FirstName = "Mario",
                            LastName = "Filling",
                            OnSite = false,
                            PhoneNr = "0703827665"
                        },
                        new
                        {
                            ID = 40,
                            DepartmentId = 1,
                            FirstName = "Benjamin",
                            LastName = "Daniels",
                            OnSite = false,
                            PhoneNr = "0707999796"
                        },
                        new
                        {
                            ID = 41,
                            DepartmentId = 1,
                            FirstName = "Mattias",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0703385890"
                        },
                        new
                        {
                            ID = 42,
                            DepartmentId = 2,
                            FirstName = "Ali",
                            LastName = "Kvackzelius",
                            OnSite = true,
                            PhoneNr = "0707644642"
                        },
                        new
                        {
                            ID = 43,
                            DepartmentId = 1,
                            FirstName = "Kristian",
                            LastName = "Askrafvsfader",
                            OnSite = true,
                            PhoneNr = "0704797059"
                        },
                        new
                        {
                            ID = 44,
                            DepartmentId = 2,
                            FirstName = "Mattias",
                            LastName = "Springsteen",
                            OnSite = true,
                            PhoneNr = "0709045804"
                        },
                        new
                        {
                            ID = 45,
                            DepartmentId = 2,
                            FirstName = "Kristian",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0703232983"
                        },
                        new
                        {
                            ID = 46,
                            DepartmentId = 1,
                            FirstName = "Gandalf",
                            LastName = "Askrafvsfader",
                            OnSite = true,
                            PhoneNr = "0703482312"
                        },
                        new
                        {
                            ID = 47,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Sork",
                            OnSite = false,
                            PhoneNr = "0701930227"
                        },
                        new
                        {
                            ID = 48,
                            DepartmentId = 1,
                            FirstName = "Tyrion",
                            LastName = "Askrafvsfader",
                            OnSite = true,
                            PhoneNr = "0702347394"
                        },
                        new
                        {
                            ID = 49,
                            DepartmentId = 2,
                            FirstName = "Sauron",
                            LastName = "Sainz",
                            OnSite = true,
                            PhoneNr = "0707046938"
                        },
                        new
                        {
                            ID = 50,
                            DepartmentId = 2,
                            FirstName = "Benjamin",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0709361946"
                        },
                        new
                        {
                            ID = 51,
                            DepartmentId = 2,
                            FirstName = "Stina",
                            LastName = "Filling",
                            OnSite = true,
                            PhoneNr = "0703306541"
                        },
                        new
                        {
                            ID = 52,
                            DepartmentId = 1,
                            FirstName = "Sauron",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0709072981"
                        },
                        new
                        {
                            ID = 53,
                            DepartmentId = 1,
                            FirstName = "Lisa",
                            LastName = "Gandhi",
                            OnSite = true,
                            PhoneNr = "0706713201"
                        },
                        new
                        {
                            ID = 54,
                            DepartmentId = 1,
                            FirstName = "Obi-Wan",
                            LastName = "Segelspjut",
                            OnSite = true,
                            PhoneNr = "0707348668"
                        },
                        new
                        {
                            ID = 55,
                            DepartmentId = 2,
                            FirstName = "Obi-Wan",
                            LastName = "Ramone",
                            OnSite = false,
                            PhoneNr = "0705022184"
                        },
                        new
                        {
                            ID = 56,
                            DepartmentId = 1,
                            FirstName = "Carla",
                            LastName = "Vader",
                            OnSite = true,
                            PhoneNr = "0703935736"
                        },
                        new
                        {
                            ID = 57,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Von Röfvenstråhle",
                            OnSite = true,
                            PhoneNr = "0708317501"
                        },
                        new
                        {
                            ID = 58,
                            DepartmentId = 1,
                            FirstName = "Krösus",
                            LastName = "Vader",
                            OnSite = true,
                            PhoneNr = "0705917194"
                        },
                        new
                        {
                            ID = 59,
                            DepartmentId = 2,
                            FirstName = "Krösus",
                            LastName = "Kenttä",
                            OnSite = true,
                            PhoneNr = "0702922392"
                        },
                        new
                        {
                            ID = 60,
                            DepartmentId = 1,
                            FirstName = "Kristian",
                            LastName = "Anka",
                            OnSite = true,
                            PhoneNr = "0703164559"
                        },
                        new
                        {
                            ID = 61,
                            DepartmentId = 2,
                            FirstName = "Sauron",
                            LastName = "Daniels",
                            OnSite = true,
                            PhoneNr = "0708494329"
                        },
                        new
                        {
                            ID = 62,
                            DepartmentId = 1,
                            FirstName = "Obi-Wan",
                            LastName = "Woltersson",
                            OnSite = true,
                            PhoneNr = "0703366846"
                        },
                        new
                        {
                            ID = 63,
                            DepartmentId = 1,
                            FirstName = "Carlos",
                            LastName = "Ek",
                            OnSite = true,
                            PhoneNr = "0702090193"
                        },
                        new
                        {
                            ID = 64,
                            DepartmentId = 1,
                            FirstName = "Carla",
                            LastName = "Gråskägge",
                            OnSite = true,
                            PhoneNr = "0704800307"
                        },
                        new
                        {
                            ID = 65,
                            DepartmentId = 2,
                            FirstName = "Carla",
                            LastName = "Lannister",
                            OnSite = true,
                            PhoneNr = "0703848073"
                        },
                        new
                        {
                            ID = 66,
                            DepartmentId = 2,
                            FirstName = "Kalle",
                            LastName = "Fritjiofsdottir",
                            OnSite = true,
                            PhoneNr = "0702928516"
                        },
                        new
                        {
                            ID = 67,
                            DepartmentId = 1,
                            FirstName = "Obi-Wan",
                            LastName = "Ramone",
                            OnSite = true,
                            PhoneNr = "0706057234"
                        },
                        new
                        {
                            ID = 68,
                            DepartmentId = 2,
                            FirstName = "Mario",
                            LastName = "Pruselius",
                            OnSite = true,
                            PhoneNr = "0703676971"
                        },
                        new
                        {
                            ID = 69,
                            DepartmentId = 1,
                            FirstName = "Katja",
                            LastName = "Kenttä",
                            OnSite = false,
                            PhoneNr = "0701442496"
                        },
                        new
                        {
                            ID = 70,
                            DepartmentId = 2,
                            FirstName = "Krösus",
                            LastName = "Krunkenstör",
                            OnSite = true,
                            PhoneNr = "0707433827"
                        });
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Procedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Procedures")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Schedule", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Staff", "Staff")
                        .WithMany("Schedules")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.ScheduledProcedure", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Procedure", "Procedure")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalTaskManagerWebAPI.Models.Schedule", "Schedule")
                        .WithMany("ScheduledProcedures")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HospitalTaskManagerWebAPI.Models.Staff", b =>
                {
                    b.HasOne("HospitalTaskManagerWebAPI.Models.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
